version: '3.8'

name: parkolo_backend_hf

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: parking_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/parking_db
    depends_on:
      - db

volumes:
  postgres_data: